#JWT token validity in seconds
jwt:
  secret: secret
  token:
    validity: 10000
server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: changeit
    key-store-type: pkcs12
    key-alias: springboot
    key-password: changeit
  port: 8443
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration